# Generated by Django 4.0.8 on 2022-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_accounttype_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='link_to_binary',
            field=models.BooleanField(default=False),
        ),
    ]
