# Generated by Django 4.0.8 on 2022-11-22 00:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_remove_image_binary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='binaryimagelink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='binaryimagelink',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='binaryimagelink',
            name='expiring_time',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
