# Generated by Django 4.0.8 on 2022-11-23 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_binaryimagelink_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binaryimagelink',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 16, 5, 29, 442552), editable=False),
        ),
        migrations.AlterField(
            model_name='binaryimagelink',
            name='expiration_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='binaryimagelink',
            name='expiring_time',
            field=models.IntegerField(null=True),
        ),
    ]
