# Generated by Django 4.0.8 on 2022-11-23 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_alter_binaryimagelink_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binaryimagelink',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 20, 53, 21, 150186), editable=False),
        ),
    ]
